// ed_sim_mem.v

// Generated using ACDS version 24.3.1 102

`timescale 1 ps / 1 ps
module ed_sim_mem (
		input  wire [0:0]  mem_cke_0,     //       mem_0.mem_cke
		input  wire [0:0]  mem_cs_0,      //            .mem_cs
		input  wire [5:0]  mem_ca_0,      //            .mem_ca
		inout  wire [31:0] mem_dq_0,      //            .mem_dq
		inout  wire [3:0]  mem_dqs_t_0,   //            .mem_dqs_t
		inout  wire [3:0]  mem_dqs_c_0,   //            .mem_dqs_c
		inout  wire [3:0]  mem_dmi_0,     //            .mem_dmi
		input  wire [0:0]  mem_ck_t_0,    //    mem_ck_0.mem_ck_t
		input  wire [0:0]  mem_ck_c_0,    //            .mem_ck_c
		output wire        oct_rzqin_0,   //       oct_0.oct_rzqin
		input  wire        mem_reset_n_0  // mem_reset_n.mem_reset_n
	);

	altera_emif_lpddr4_model_top #(
		.MEM_CS_WIDTH       (1),
		.MEM_NUM_RANKS      (1),
		.MEM_CKE_WIDTH      (1),
		.MEM_CK_C_WIDTH     (1),
		.MEM_CK_T_WIDTH     (1),
		.MEM_BA_WIDTH       (3),
		.MEM_ROW_ADDR_WIDTH (17),
		.MEM_COL_ADDR_WIDTH (10),
		.MEM_DQ_WIDTH       (32),
		.MEM_CA_WIDTH       (6),
		.MEM_DMI_WIDTH      (4),
		.MEM_DQS_C_WIDTH    (4),
		.MEM_DQS_T_WIDTH    (4),
		.MEM_RESET_N_WIDTH  (1)
	) emif_io96b_mem_model_lpddr4_inst (
		.mem_cke_0     (mem_cke_0),     //   input,   width = 1,       mem_0.mem_cke
		.mem_cs_0      (mem_cs_0),      //   input,   width = 1,            .mem_cs
		.mem_ca_0      (mem_ca_0),      //   input,   width = 6,            .mem_ca
		.mem_dq_0      (mem_dq_0),      //   inout,  width = 32,            .mem_dq
		.mem_dqs_t_0   (mem_dqs_t_0),   //   inout,   width = 4,            .mem_dqs_t
		.mem_dqs_c_0   (mem_dqs_c_0),   //   inout,   width = 4,            .mem_dqs_c
		.mem_dmi_0     (mem_dmi_0),     //   inout,   width = 4,            .mem_dmi
		.mem_ck_t_0    (mem_ck_t_0),    //   input,   width = 1,    mem_ck_0.mem_ck_t
		.mem_ck_c_0    (mem_ck_c_0),    //   input,   width = 1,            .mem_ck_c
		.oct_rzqin_0   (oct_rzqin_0),   //  output,   width = 1,       oct_0.oct_rzqin
		.mem_reset_n_0 (mem_reset_n_0)  //   input,   width = 1, mem_reset_n.mem_reset_n
	);

endmodule
