// ed_sim_ref_clk_source_0.v

// Generated using ACDS version 24.3.1 102

`timescale 1 ps / 1 ps
module ed_sim_ref_clk_source_0 #(
		parameter CLOCK_RATE = 100000000,
		parameter CLOCK_UNIT = 1
	) (
		output wire  clk  // clk.clk
	);

	altera_avalon_clock_source #(
		.CLOCK_RATE (CLOCK_RATE),
		.CLOCK_UNIT (CLOCK_UNIT)
	) altera_avalon_clock_source_inst (
		.clk (clk)  //  output,  width = 1, clk.clk
	);

endmodule
