// ed_sim_reset_handler.v

// Generated using ACDS version 24.3.1 102

`timescale 1 ps / 1 ps
module ed_sim_reset_handler (
		input  wire  reset_n_0,   //   reset_n_0.reset_n
		input  wire  conduit_0,   //   conduit_0.export
		input  wire  clk,         //         clk.clk
		output wire  reset_out_n  // reset_n_out.reset_n
	);

	ed_sim_reset_handler_mem_reset_handler_100_tz6himy #(
		.SYNC_TO_CLK       (1),
		.USE_AND_GATE      (1),
		.NUM_RESETS        (1),
		.NUM_CONDUITS      (1),
		.CONDUIT_INVERT_0  (0),
		.CONDUIT_INVERT_1  (0),
		.CONDUIT_INVERT_2  (0),
		.CONDUIT_INVERT_3  (0),
		.CONDUIT_INVERT_4  (0),
		.CONDUIT_INVERT_5  (0),
		.CONDUIT_INVERT_6  (0),
		.CONDUIT_INVERT_7  (0),
		.CONDUIT_INVERT_8  (0),
		.CONDUIT_INVERT_9  (0),
		.CONDUIT_INVERT_10 (0),
		.CONDUIT_INVERT_11 (0),
		.CONDUIT_INVERT_12 (0),
		.CONDUIT_INVERT_13 (0),
		.CONDUIT_INVERT_14 (0),
		.CONDUIT_INVERT_15 (0)
	) mem_reset_handler_inst (
		.reset_n_0   (reset_n_0),   //   input,  width = 1,   reset_n_0.reset_n
		.conduit_0   (conduit_0),   //   input,  width = 1,   conduit_0.export
		.clk         (clk),         //   input,  width = 1,         clk.clk
		.reset_out_n (reset_out_n), //  output,  width = 1, reset_n_out.reset_n
		.reset_n_1   (1'b1),        // (terminated),                         
		.reset_n_2   (1'b1),        // (terminated),                         
		.reset_n_3   (1'b1),        // (terminated),                         
		.reset_n_4   (1'b1),        // (terminated),                         
		.reset_n_5   (1'b1),        // (terminated),                         
		.reset_n_6   (1'b1),        // (terminated),                         
		.reset_n_7   (1'b1),        // (terminated),                         
		.reset_n_8   (1'b1),        // (terminated),                         
		.reset_n_9   (1'b1),        // (terminated),                         
		.reset_n_10  (1'b1),        // (terminated),                         
		.reset_n_11  (1'b1),        // (terminated),                         
		.reset_n_12  (1'b1),        // (terminated),                         
		.reset_n_13  (1'b1),        // (terminated),                         
		.reset_n_14  (1'b1),        // (terminated),                         
		.reset_n_15  (1'b1),        // (terminated),                         
		.conduit_1   (1'b0),        // (terminated),                         
		.conduit_2   (1'b0),        // (terminated),                         
		.conduit_3   (1'b0),        // (terminated),                         
		.conduit_4   (1'b0),        // (terminated),                         
		.conduit_5   (1'b0),        // (terminated),                         
		.conduit_6   (1'b0),        // (terminated),                         
		.conduit_7   (1'b0),        // (terminated),                         
		.conduit_8   (1'b0),        // (terminated),                         
		.conduit_9   (1'b0),        // (terminated),                         
		.conduit_10  (1'b0),        // (terminated),                         
		.conduit_11  (1'b0),        // (terminated),                         
		.conduit_12  (1'b0),        // (terminated),                         
		.conduit_13  (1'b0),        // (terminated),                         
		.conduit_14  (1'b0),        // (terminated),                         
		.conduit_15  (1'b0)         // (terminated),                         
	);

endmodule
